### ISSUE TITLE
请问如何设置服务器定时重启呀

### ISSUE THREAD

**Issue by ZokiJava** [tydaytygx/cs2-server-guide#1]
和自动输入一些设置，每次打开都要手动输入一些设置比如：热身时间，金钱数量等等。服务器开了一天之后游戏里就变得好卡，关了再重新开才能解决TXT

**Comment by tydaytygx** [comment]
感谢你对教程提供的反馈和建议！

# 定时重启
确实是有开久了变卡的情况，

定时重启可以使用
crontab

例如crontab -e
```conf
0 4 * * * docker restart cs2-dedicated
``` 
每天凌晨四点就会重启了

# 自定义配置
自定义配置的路径
```cs2-dedicated/game/csgo/cfg```

以竞技模式为例

gamemode_competitive.cfg

修改服务端全局配置

gamemode_server.txt

**Comment by tydaytygx** [comment]
已添加到说明中
